package my.javacraft.elastic.model;

import jakarta.validation.constraints.NotEmpty;
import java.nio.charset.StandardCharsets;
import java.util.UUID;
import lombok.Data;
import lombok.ToString;

@Data
@ToString
public class UserHistory {
    @NotEmpty
    Long count;
    @NotEmpty
    String updated;
    @NotEmpty
    String elasticId;
    @NotEmpty
    UserClick userClick;

    public UserHistory() {} // we need default constructor for jackson

    public UserHistory(String updated, UserClick userClick) {
        this.count = 1L;
        this.updated = updated;
        this.elasticId = getElasticId(userClick);
        this.userClick = userClick;
    }

    public String getElasticId(UserClick userClick) {
        // Elasticsearch autogenerated IDs uses a form of base64 encoding, see TimeBasedUUIDGenerator (repo: elastic/elasticsearch)
        // _id is limited to 512 bytes in size and larger values will be rejected, that means we should limit how we generated id.
        // UUID.nameUUIDFromBytes uses 3rd UUID type (Name-based)
        return UUID.nameUUIDFromBytes("%s_%s_%s_%s".formatted(
                userClick.getUserId(),
                userClick.getDocumentId(),
                userClick.getSearchType(),
                userClick.getSearchPattern()
        ).getBytes(StandardCharsets.UTF_8)).toString();
    }
}
