server:
  port: 8053

spring:
  application:
    name: ses-app
  datasource:
    url: jdbc:postgresql://localhost:5434/ses
    username: ses
    password: ses
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    dev.nklip.javacraft.ses: INFO
